repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # black version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1  # isort version
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2  # flake8 version
    hooks:
      - id: flake8
        args: [--max-line-length=119,]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.8.0  # mypy version
#    hooks:
#      - id: mypy
#        args:
#          - --exclude
#          - '^(tests|alembic)/.*'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # hooks version
    hooks:
      - id: trailing-whitespace