services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_theater
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - theater_network

  minio:
    image: minio/minio
    container_name: minio_theater
    entrypoint: sh
    command: [ "-c", "minio server --console-address ':9001' /data" ]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - theater_network

  web:
    build: .
    container_name: web_theater
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/usr/src/fastapi"]
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/fastapi
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./src:/usr/src/fastapi
    depends_on:
      - mailhog
      - minio
    networks:
      - theater_network

  redis:
    image: redis:alpine
    container_name: redis_theater
    ports:
      - "6379:6379"
    networks:
      - theater_network

  celery:
    build: .
    container_name: celery_theater
    command: [ "poetry", "run", "celery", "-A", "app.celery", "worker", "--loglevel=info" ]
    depends_on:
      - redis
    volumes:
      - ./src:/usr/src/fastapi
    networks:
      - theater_network

  celery-beat:
    build: .
    container_name: celery_beat_theater
    command: [ "poetry", "run", "celery", "-A", "app.celery", "beat", "--loglevel=info" ]
    depends_on:
      - redis
    volumes:
      - ./src:/usr/src/fastapi
    networks:
      - theater_network

networks:
  theater_network:
    driver: bridge

volumes:
  mailhog_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local