"""Initial migration

Revision ID: 0e4c6efe6a3e
Revises:
Create Date: 2025-03-22 09:52:13.974363

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e4c6efe6a3e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("movies_certification_id_fkey", "movies", type_="foreignkey")
    op.drop_constraint("movie_stars_star_id_fkey", "movie_stars", type_="foreignkey")
    op.drop_constraint("movie_genres_movie_id_fkey", "movie_genres", type_="foreignkey")
    op.drop_constraint(
        "movie_directors_movie_id_fkey", "movie_directors", type_="foreignkey"
    )

    op.drop_table("certifications")
    op.drop_table("stars")
    op.drop_table("movie_stars")
    op.drop_table("movies")
    op.drop_table("movie_directors")
    op.drop_table("movie_genres")
    op.drop_table("directors")
    op.drop_table("genres")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('genres_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="genres_pkey"),
        sa.UniqueConstraint("name", name="genres_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "directors",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('directors_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="directors_pkey"),
        sa.UniqueConstraint("name", name="directors_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "movie_genres",
        sa.Column("movie_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("genre_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name="movie_genres_genre_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
            name="movie_genres_movie_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("movie_id", "genre_id", name="movie_genres_pkey"),
    )
    op.create_table(
        "movie_directors",
        sa.Column("movie_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("director_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["directors.id"],
            name="movie_directors_director_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
            name="movie_directors_movie_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("movie_id", "director_id", name="movie_directors_pkey"),
    )
    op.create_table(
        "movies",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('movies_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("uuid", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("time", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "imdb",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("votes", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "meta_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "gross",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RELEASED", "POST_PRODUCTION", "IN_PRODUCTION", name="moviestatusenum"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "certification_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["certifications.id"],
            name="movies_certification_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="movies_pkey"),
        sa.UniqueConstraint("name", "year", "time", name="unique_movie_constraint"),
        sa.UniqueConstraint("uuid", name="movies_uuid_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "movie_stars",
        sa.Column("movie_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("star_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
            name="movie_stars_movie_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["star_id"],
            ["stars.id"],
            name="movie_stars_star_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("movie_id", "star_id", name="movie_stars_pkey"),
    )
    op.create_table(
        "stars",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="stars_pkey"),
        sa.UniqueConstraint("name", name="stars_name_key"),
    )
    op.create_table(
        "certifications",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="certifications_pkey"),
        sa.UniqueConstraint("name", name="certifications_name_key"),
    )
    # ### end Alembic commands ###
