"""Added finalizing models

Revision ID: df94cc309fbb
Revises: fee5d6bf46d1
Create Date: 2025-03-26 11:12:01.596808

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df94cc309fbb"
down_revision: Union[str, None] = "fee5d6bf46d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comment_likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("likes")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_constraint("comments_parent_comment_id_fkey", type_="foreignkey")
        batch_op.drop_column("parent_comment_id")

    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.Boolean(), nullable=False))

    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("amount", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("is_purchased", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_column("is_purchased")
        batch_op.drop_column("amount")

    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_column("status")

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "parent_comment_id", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.create_foreign_key(
            "comments_parent_comment_id_fkey", "comments", ["parent_comment_id"], ["id"]
        )

    op.create_table(
        "likes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("movie_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["comments.id"], name="likes_comment_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"], ["movies.id"], name="likes_movie_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="likes_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="likes_pkey"),
    )
    op.drop_table("comment_likes")
    op.drop_table("movie_likes")
    # ### end Alembic commands ###
